//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nike.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int SlideId { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
